### ISSUE TITLE
Issue related to the package

### ISSUE THREAD

**Issue by Chakru** [VinayakBagaria/Bunker-Attender#1]
While doing the "pip install --trusted-host pypi.python.org pckg_name" an error is throwing up. The error thrown is as follows:
"Collecting pckg_name
  Could not find a version that satisfies the requirement pckg_name (from versions: )
No matching distribution found for pckg_name"
Kindly look into the matter.
Thanks.

**Comment by VinayakBagaria** [comment]
pckg_name stands for the package you want. Like django, requests, etc
